file_format: "1"
id: sweep
name: Sweep
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - sweep_left
  - sweep_right
